<?xml version="1.0"?>
<!DOCTYPE transcriptions [
	<!ELEMENT transcription (url,title?,body)>
	<!ELEMENT url (#PCDATA)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT body (panel+, line+)>
	<!ELEMENT panel (#PCDATA)>
	<!ELEMENT line (#PCDATA)>
]>
<transcriptions>
	<transcription>
		<url>qwantz.com/index.php?comic=1</url>
		<title>today is a beautiful day</title>
		<body>
			<panel>
				<line>T-Rex: Today is a beautiful day to be stomping on things! As a dinosaur, stomping on things is the best part of my day, indeed!</line>
				<line>T-Rex: *gasp*</line>
				<line>T-Rex: What&apos;s that, little house? You wish you were back in your own time? THAT IS TOO BAD FOR YOU</line>
				<line>T-Rex: Perhaps you too will get a stomping, little girl!</line>
				<line>Utahraptor: WAIT!</line>
				<line>Utahraptor: Is stomping really the answer to your problem(s)?</line>
				<line>T-Rex: Problem(s)?</line>
				<line>T-Rex: My only problem(s) have to do with you interrupting my stomping!</line>
				<line>T-Rex: (in small text) crazy utahraptor!</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=10</url>
		<title>utaught me how to be a stupid jerk!</title>
		<body>
			<panel>
				<line>T-Rex: I have felt the harsh sting of my own racial joke turned against me! Luckily, I&apos;ve been saving a joke for just such an occasion.</line>
				<line>T-Rex: All of those hours of thinking up insults for hypothetical enemies has finally paid off!</line>
				<line>T-Rex: So, my racist joke somehow backfired on me.</line>
				<line>Dromeciomimus: I hope that&apos;s the last time you ever say that sentence.</line>
				<line>T-Rex: Well, I&apos;ve made up my own joke to get him today. All I need to do is &quot;find that Utahraptor!&quot;</line>
				<line>T-Rex: I hope the Utahraptor is around here somewhere! My legs are giving tired.</line>
				<line>Utahraptor: I&apos;m behind you.</line>
				<line>T-Rex: There you are! Knock, knock.</line>
				<line>Utahraptor: Who&apos;s there?</line>
				<line>T-Rex: Utah.</line>
				<line>Utahraptor:*sigh* Utah who?</line>
				<line>T-Rex: Utaught me how to be a stupid jerk!</line>
				<line>T-Rex: And I was a very good student!</line>
				<line>Utahraptor: Do you even listen to yourself?</line>
				<line>T-Rex: No, but-- see, I learned it from you!</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=100</url>
		<title>a journey to the moon</title>
		<body>
			<panel>
				<line>Narrator: A JOURNEY TO THE MOON</line>
				<line>Narrator: A RARE PROPOSITION</line>
				<line>T-Rex: I propose a journey to the moon!</line>
				<line>Narrator: SEVEN YEARS LATER...</line>
				<line>T-Rex: I have constructed a rocket-ship for myself and a guest of my choosing! The wood from this house will provide the fuel!</line>
				<line>Dromiceiomimus: May I be your guest?</line>
				<line>T-Rex: I will give your offer my consideration?</line>
				<line>Narrator: ON THE MOON...</line>
				<line>T-Rex: Lunar women are good for stomping!</line>
				<line>Utahraptor: Thanks for choosing me, T-Rex!</line>
				<line>Narrator: A RETURN TO EARTH!</line>
				<line>Utahraptor: Let&apos;s do that again sometime!</line>
				<line>T-Rex: I concede it easily!</line>
				<line>Narrator: A NEW DAY DAWNS...</line>
				<line>T-Rex: Now, where is my wallet?</line>
				<line>T-Rex: OH shoot!</line>
				<line>T-Rex: IT IS ON THE MOON</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=100</url>
		<title>a journey to the moon</title>
		<body>
			<panel>
				<line>Narrator: A JOURNEY TO THE MOON</line>
				<line>Narrator: A RARE PROPOSITION</line>
				<line>T-Rex: I propose a journey to the moon!</line>
				<line>Narrator: SEVEN YEARS LATER...</line>
				<line>T-Rex: I have constructed a rocket-ship for myself and a guest of my choosing! The wood from this house will provide the fuel!</line>
				<line>Dromiceiomimus: May I be your guest?</line>
				<line>T-Rex: I will give your offer my consideration?</line>
				<line>Narrator: ON THE MOON...</line>
				<line>T-Rex: Lunar women are good for stomping!</line>
				<line>Utahraptor: Thanks for choosing me, T-Rex!</line>
				<line>Narrator: A RETURN TO EARTH!</line>
				<line>Utahraptor: Let&apos;s do that again sometime!</line>
				<line>T-Rex: I concede it easily!</line>
				<line>Narrator: A NEW DAY DAWNS...</line>
				<line>T-Rex: Now, where is my wallet?</line>
				<line>T-Rex: OH shoot!</line>
				<line>T-Rex: IT IS ON THE MOON</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1000</url>
		<title>Kangaroo Kicking Record</title>
		<body>
			<panel>
				<line>Narrator: FOUR YEARS AGO:</line>
				<line>T-Rex: Today is a good day I think for being remembered! My lovely visage, callipygian frame, startlingly awesome calves and charming smile will yet go down in history! And how will I be immortalized?</line>
				<line>T-Rex: I will be immortalized by kicking an evil kangaroo one thousand times. Right in the bum!</line>
				<line>T-Rex: And YEAH, kicking a kangaroo in the bum has PROBABLY been done before, but never one thousand times! That&apos;s the secret to immortality: pick a direction and go SO FAR OUT in it that anyone who points to you will have to say, &quot;Here, this is as far as anyone needs to go.&quot; Then, hey presto, you&apos;re immortalized! You&apos;re the dude who kicked an evil kangaroo as often as evil kangaroos could ever need be kicked- probably more often, actually.</line>
				<line>Utahraptor: So you&apos;re going for recordbook immortality?</line>
				<line>T-Rex: Crazy utahraptor!!</line>
				<line>T-Rex: I&apos;m going for STUNT immortality. I&apos;ll just keep kicking that kangaroo until even if somebody wanted to catch up, they&apos;d look at my record and say &quot;Well, THAT&apos;S totally not worth doing&quot;.</line>
				<line>Utahraptor: I guess, if that&apos;s how you want to spend your life.</line>
				<line>T-Rex: IT APPARENTLY IS</line>
				<line>Narrator: FOUR YEARS LATER:</line>
				<line>T-Rex: Aw shoot, I was supposed to be kicking kangaroos all this time!</line>
				<line>GOD: LOOKS LIKE PEOPLE WILL JUST REMEMBER YOU FOR TALKING A BIG GAME MY FRIEND</line>
				<line>T-Rex: I will take what I can get!!</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1001</url>
		<title>it&apos;s called &apos;life of crime&apos; and it&apos;s extremely excellent.  you should buy one.</title>
		<body>
			<panel>
				<line>T-Rex: I&apos;ve thought of the best story!  Oh goodness.  This story will make me RICH.  It will make me PRIME MINISTER of being rich.  I will be awarded a doctorate in APPLIED RICHOLOGY.</line>
				<line>T-Rex: I can only hope the world is ready for it!</line>
				<line>T-Rex: So BASICALLY in the story there&apos;s all this build up about this kid whose parents named her Crime and how she grows into her name and becomes this big arch-criminal!  The cops are powerless to stop her, even the really really good ones.  ESPECIALLY the really really good ones.  Anyway it&apos;s narrated in the third person and at the end of the book Crime goes out on a few dates with the narrator and then he abruptly stops writing because he&apos;s all cheezed at her.  The end!</line>
				<line>Utahraptor: But - why is he all cheezed at her?</line>
				<line>T-Rex: Because he always has to pay for everything!</line>
				<line>T-Rex: Get it?  Because CRIME DOESN&apos;T PAY!!  Listen, my story has both a hilarious twist ending and also an important message regarding the paying of crime.</line>
				<line>T-Rex: Dear mental diary that everyone can hear:  Utahraptor was so impressed with my book idea that he forgot how to talk!</line>
				<line>Utahraptor:  I didn&apos;t forget how to talk!  I just forgot how to shoot down your idea politely!</line>
				<line>T-Rex: Utahraptor!!  DON&apos;T LISTEN TO MY DIARY!</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1002</url>
		<title>as a bonus, &apos;life of crime&apos; is included as an illustrative anecdote at the end of the book.  STRAIGHT TO NUMBER ONE ON THE NEW YORK TIMES, BABY!</title>
		<body>
			<panel>
				<line>Narrator: DATING TIPS COMICS</line>
				<line>Narrator: now featuring: tips i found in this one book!</line>
				<line>T-Rex: Here are some HOT TIPS FOR FIRST DATES, cats and kittens!</line>
				<line>T-Rex: Okay! The first tip is this: to find out if your date is REALLY into you, all you have to do is push a salt shaker over to their side of the table! If he&apos;s interested in you, he&apos;ll pick it up and play with it, but if he&apos;s NOT interested, he&apos;ll push it back to your side. The salt shaker represents your feelings, here, okay? And playing with a salt shaker represents ROMANTIC INTENT.</line>
				<line>Utahraptor: That&apos;s stupid! It&apos;s semantically overloading practical actions.</line>
				<line>T-Rex: See, I thought so too!</line>
				<line>T-Rex: But I just thought I was crazy, because why would someone put out a dating book if all they had were sucky tips that can TOTALLY FAIL if the guy just wants saltier, and therefore tastier, fries? I could write a better dating book. IN FACT...!</line>
				<line>Utahraptor: Aw no, no, you don&apos;t -</line>
				<line>Narrator: MEET SOMEONE WHO DOESN&apos;T SUCK THEN TRY KISSING THEM</line>
				<line>Narrator: A BOOK THAT WAS WRITTEN BY A MAN</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1002</url>
		<title>as a bonus, &apos;life of crime&apos; is included as an illustrative anecdote at the end of the book.  STRAIGHT TO NUMBER ONE ON THE NEW YORK TIMES, BABY!</title>
		<body>
			<panel>
				<line>Narrator: DATING TIPS COMICS</line>
				<line>Narrator: now featuring: tips i found in this one book!</line>
				<line>T-Rex: Here are some HOT TIPS FOR FIRST DATES, cats and kittens!</line>
				<line>T-Rex: Okay! The first tip is this: to find out if your date is REALLY into you, all you have to do is push a salt shaker over to their side of the table! If he&apos;s interested in you, he&apos;ll pick it up and play with it, but if he&apos;s NOT interested, he&apos;ll push it back to your side. The salt shaker represents your feelings, here, okay? And playing with a salt shaker represents ROMANTIC INTENT.</line>
				<line>Utahraptor: That&apos;s stupid! It&apos;s semantically overloading practical actions.</line>
				<line>T-Rex: See, I thought so too!</line>
				<line>T-Rex: But I just thought I was crazy, because why would someone put out a dating book if all they had were sucky tips that can TOTALLY FAIL if the guy just wants saltier, and therefore tastier, fries? I could write a better dating book. IN FACT...!</line>
				<line>Utahraptor: Aw no, no, you don&apos;t -</line>
				<line>Narrator: MEET SOMEONE WHO DOESN&apos;T SUCK THEN TRY KISSING THEM</line>
				<line>Narrator: A BOOK THAT WAS WRITTEN BY A MAN</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1003</url>
		<title>T-REX didn&apos;t you learn anything from the beatles you don&apos;t SAY that</title>
		<body>
			<panel>
				<line>T-Rex: It&apos;s been three days and neither &quot;Life of Crime&quot; nor &quot;Meet Someone who Doesn&apos;t Suck&quot; have made me rich. MAYBE I AM NOT THAT GREAT AN AUTHOR??</line>
				<line>T-Rex: Or maybe PEOPLE are not that great an audience!</line>
				<line>Dromiceiomimus: Or maybe you have to wait longer for a book to turn a profit!</line>
				<line>T-Rex: Or MAYBE I should be happy that I basically wrote two books in as many days, and got them published in an afternoon, and that&apos;s kinda impressive even if they aren&apos;t selling that well so far??</line>
				<line>Utahraptor: Or maybe if they were selling well, you wouldn&apos;t know it yet!</line>
				<line>T-Rex: THAT&apos;S RIGHT!</line>
				<line>T-Rex: Maybe I really am great, just impatient, and when I get home tonight there&apos;ll be a sales report in the mail showing how my books are now TEN TIMES MORE POPULAR THAN THE BIBLE. It would make sense, since they have like twenty times as many jokes in them!</line>
				<line>Utahraptor: Maybe?</line>
				<line>God: OR MAYBE I JUST DIDN&apos;T PUT MANY JOKES IN THE BIBLE BECAUSE OF TRANSLATION ISSUES.</line>
				<line>T-Rex: Hey everyone! You know what needs more jokes? ONLY EVERY RELIGIOUS TEXT EVER!!</line>
				<line>God: AW MAN - NOW WHAT AM I GONNA DO WITH ALL THESE RAISED EXPECTATIONS</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1004</url>
		<title>t-rex is brushing his hands together in the last panel, in the way that one is inclined to do when one has solved a problem Once And For All</title>
		<body>
			<panel>
				<line>T-Rex: Alright! Time to start some INTERNET BUSINESSES.</line>
				<line>T-Rex: For profits!</line>
				<line>Narrator: SOON:</line>
				<line>T-Rex: Ladies and gentlemen, I give you: easydudes.com!</line>
				<line>T-Rex: It&apos;s an easy way for you to meet new dudes! If you move to a new town and want to meet some dudes then you can go to the site and then you can meet some. On the COMPUTER!</line>
				<line>Dromiceiomimus: It sounds a little more like a service to hook people up with sexually permissive and sexually available dudes, T-Rex!</line>
				<line>T-Rex: Drat! It DOES. Another brilliant idea ruined by a hilarious double entendre.</line>
				<line>Narrator: SOON:</line>
				<line>T-Rex: Okay, so my new idea is to give the homeless access to mail, email, and a phone number!</line>
				<line>Utahraptor: Nice!</line>
				<line>Utahraptor: It can be hard for the homeless to get jobs when they can&apos;t provide callback information, so this will be a useful service. Good show, T-Rex!</line>
				<line>T-Rex: Yes, thank you! I think the world will be altered positively by BumAccess4All Dot Net.</line>
				<line>Narrator: SOON:</line>
				<line>T-Rex: There! Now I&apos;ve got a certificate from the mayor that says I&apos;m not allowed to name anything ever!</line>
				<line>T-Rex: THAT should finally straighten up some things around here!</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1005</url>
		<title>being a founder of modern philosophy is nothing but ess tea arr ee ess ess</title>
		<body>
			<panel>
				<line>T-Rex: Descartes was a dude who wrote &quot;Cogito ergo sum&quot; which means &quot;I think, therefore I am&quot;. PRETTY NEAT, cats and kittens!</line>
				<line>T-Rex: But also...PRETTY FLAWED??</line>
				<line>T-Rex: The whole deal with &quot;I think, therefore I am&quot; is that Descartes is all &quot;DAAAAAAMN, I can&apos;t be sure of ANYTHING!  My senses are flawed.  All I know for sure is I keep STRESSIN&apos; about this stuff!&quot; and then his girlfriend is all &quot;If you&apos;re so hung up on this then you must exist, huh baby?&quot; and Descartes is all &quot;Yes. That is true. I will write this down in Latin.&quot;</line>
				<line>T-Rex: That is how it went down.</line>
				<line>Utahraptor: So what&apos;s the problem, besides your unnecessary storytelling?</line>
				<line>T-Rex: Descartes&apos; girlfriend!</line>
				<line>T-Rex: She&apos;s making a huge logical leap! It&apos;s indisputible that thinking is going on, right, but we don&apos;t know for sure that Descartes is doing the thinking! All we know for sure is that thinking is going on.</line>
				<line>Utahraptor: I agree!</line>
				<line>T-Rex: R-Really?</line>
				<line>Utahraptor: Yeah! You can&apos;t have thinking in a vacuum, so SOMETHING must exist if there&apos;s thinking going on...</line>
				<line>T-Rex &quot; Utahraptor: ...but to attribute that thinking to yourself just because you&apos;re aware of it is an awful big leap for a skeptic to make!</line>
				<line>T-Rex: OH MY GOODNESS HOW DID WE JUST DO THAT</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1006</url>
		<title>dog breederies are where you get dog breeders from.  i shouldn&apos;t have to tell you this?</title>
		<body>
			<panel>
				<line>T-Rex: Here are some things that DEFINITELY won&apos;t fit into my mouth. I tried! They won&apos;t fit.</line>
				<line>T-Rex: First off: dog breederies, solar panel processing plants, and giant cubes!</line>
				<line>T-Rex: Also: twenty cars on a stick. Sound stages, every library (individually AND en masse), medium-sized cubes that are still pretty big, lakes, beer-flavoured lakes, and beer-flavoured lakes in Minnesota.</line>
				<line>Dromiceiomimus: I know for a fact that on e of those doesn&apos;t exist, T-Rex!</line>
				<line>T-Rex: Doesn&apos;t exist in my mouth, that is!! Because it&apos;s too big?</line>
				<line>Utahraptor: Not much to talk about today, huh?</line>
				<line>T-Rex: What? There&apos;s plenty to talk about!</line>
				<line>Utahraptor: It&apos;s just, YESTERDAY you had some neat ideas about knowledge and existence, and today you&apos;re all &quot;here are some things that don&apos;t fit in my big ol&apos; mouth&quot; and your TOTALLY LYING about trying them; I can tell.</line>
				<line>T-Rex: They dovetail together nicely.</line>
				<line>Utahraptor: I don&apos;t see how!</line>
				<line>Narrator: T-REX EXPLAINS:</line>
				<line>Utahraptor: Ah, that makes perfect sense! Thanks, T-Rex! Now I know how digital timers work.</line>
				<line>T-Rex: You&apos;re welcome!</line>
				<line>T-Rex: Now, HERE&apos;S how putting the things in my mouth ties in with existence. . .</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1008</url>
		<title>where herzog fears chickens i fear cephalopods.  i feel our fear comes from the same place.</title>
		<body>
			<panel>
				<line>Narrator: COMICS IN WHICH GOD HIMSELF QUOTES WERNER HERZONG.</line>
				<line>God: LIFE IN THE OCEANS MUST BE SHEER HELL</line>
				<line>T-Rex: I guess so, huh?</line>
				<line>God: A VAST MERCILESS HELL OF PERMANENT AND IMMEDIATE DANGER</line>
				<line>T-Rex: Yep!</line>
				<line>God: SO MUCH OF A HELL THAT DURING EVOLUTION SOME SPECIES - INCLUDING MAN - CRAWLED - FLED ONTO SOME SMALL CONTINENTS OF SOLID LAND WHERE THE LESSONS OF DARKNESS CONTINUE</line>
				<line>T-Rex: That&apos;s certainly one way of looking at it, right, Dromiceiomimums?</line>
				<line>Narrator: the end</line>
				<line>Narrator: COMICS FOR TEENS today&apos;s installment: &quot;THE PRIVATE TOOTER&quot;</line>
				<line>T-Rex: what do you call a teacher who never passes gas in public?</line>
				<line>Utahraptor: What?</line>
				<line>T-Rex: A private tooter!</line>
				<line>Narrator: SECONDS LATER:</line>
				<line>T-Rex: That was an extremely hilarious joke that deserved more laughter than it received.</line>
				<line>Narrator: the end.</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1009</url>
		<title>will t-rex wear these glasses tomorrow?  SPOILER ALERT: he will probably have buyer&apos;s regret, but will still be liable to bust them out whenever he&apos;s nostalgic for 2004, OR for new year&apos;s eve 2003.</title>
		<body>
			<panel>
				<line>T-Rex: I went to the optometrist AGAIN last night, and AGAIN she said I might need to get nerd goggles!</line>
				<line>T-Rex: (She called them &quot;glasses&quot; but you can tell she was thinking &quot;nerd goggles&quot;!)</line>
				<line>T-Rex: The PROBLEM is that I define myself in terms of not having glasses! People are always &quot;Oh. You&apos;re lookng for T-Rex? He&apos;s the green tyrannosaurus rex over there! You&apos;ll be able to spot him because he&apos;s so not wearing glasses.&quot; </line>
				<line>Dromiceiomimus: Aw, I think you&apos;d look cute in them! I also think you can turn this around and make glasses your thing, you know?</line>
				<line>Narrator :SHORTLY THEREAFTER .</line>
				<line>T-Rex: Maybe Dromiceiomimus is right!</line>
				<line>Utahraptor: She usually is!</line>
				<line>T-Rex: I COULD  get some pretty kick-ass glasses. Like glasses that say &quot;WARNING: AWESOME DUDE&quot; on them! OOH, or horn-rimmed 60s housewife glasses! Sweetness!</line>
				<line>Utahraptor: You&apos;ll have to wear them every day, so maybe you&apos;ll, um, want to see how they look before you commit?</line>
				<line>Narrator: A FEW DAYS LATER: </line>
				<line>T-Rex: I&apos;m here to pick up my prescription &quot;Happy New year 2004&quot; glasses! They have a plastic &quot;2&quot; on one side and a &quot;4&quot; on the other. </line>
				<line>Optometrist Clerk: Sir, you have made an unforgettable choice.</line>
				<line>T-Rex: I like you too, optometrist clerk!</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=101</url>
		<title>onanism: a show of vocabulary descends into a masturbation joke</title>
		<body>
			<panel>
				<line>T-Rex: Here is a list of adjectives I would like to have chosen when describing me!</line>
				<line>T-Rex: 1) &quot;Sated&quot;!</line>
				<line>T-Rex: Second on the list: &quot;alluring&quot;! followed closely by &quot;stompin&apos;&quot;!</line>
				<line>T-Rex: Fourth: &quot;Callipygian&quot;, pronounced &quot;kal-lip-pee-je-en&quot; - adj: &quot;having beautifully proportioned buttocks!</line>
				<line>T-Rex: i.e.: Me</line>
				<line>T-Rex: 5) &quot;Magnanimous&quot;, which is-</line>
				<line>Utahraptor: Wait, aren&apos;t you missing one?</line>
				<line>T-Rex: Which?</line>
				<line>Utahraptor: &quot;Onanistic&quot;?</line>
				<line>T-Rex: I know what that means!!</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1010</url>
		<title>if i had a friend who was a rock star you could rename my comic to &apos;PASSIVE AGGRESSIVE DINOSAUR COMICS&apos;.  but i don&apos;t!  or if i did i&apos;m sure he&apos;d be cool!</title>
		<body>
			<panel>
				<line>Narrator: MEANWHILE, IN THE UNIVERSE WHERE T-REX IS A PROFESSIONAL SINGER:</line>
				<line>T-Rex: Rock star!</line>
				<line>Narrator: ROCK STAR</line>
				<line>T-Rex: I&apos;m a totally cool rock star!</line>
				<line>T-Rex: That&apos;s still awesome, right? It seems that 10 years ago people were more into rock stars and being rock stars than they are now. But I am a rock star and it is my job to sing rock songs on stage and in CD players!!</line>
				<line>Dromiceiomimus: Do your other rock star friends talk like that? Do they reference themselves as &quot;cool rock star[s]&quot;?</line>
				<line>T-Rex: Sometimes we do, Dromiceiomimus. BETWEEN ROCK SONGS, THAT IS!!</line>
				<line>Utahraptor: Hey, how come we never get to meet your rock star friends?</line>
				<line>T-Rex: Well - um...</line>
				<line>Utahraptor: Are you ASHAMED of us, T-Rex?</line>
				<line>T-Rex: No! They&apos;re just different people! You wouldn&apos;t get along. They like rocking and you -</line>
				<line>Utahraptor: I like rocking!</line>
				<line>T-Rex: But in DIFFERENT WAYS.</line>
				<line>T-Rex: Utahraptor, I&apos;ve got to go practice rocking out now, but can we talk about this tonight?</line>
				<line>Utahraptor [offscreen]: No! You&apos;re being a jerk!</line>
				<line>T-Rex: Utahraptor! I&apos;m super late for rocking out practice, okay?</line>
				<line>T-Rex: I&apos;m gonna need you to respect the rock, okay?</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1011</url>
		<title>the prince of zombie whales</title>
		<body>
			<panel>
				<line>T-Rex: I have some bad news: zombies are in danger of becoming old hat! It&apos;s TRUE. But I have a solution to make them interesting again: all you need is stories where not just people but ANIMALS become undead!</line>
				<line>T-Rex: Zombie whales!</line>
				<line>T-Rex: But better than that: zombie BIRDS.</line>
				<line>Dromiceiomimus: Didn&apos;t Hitchcock make a movie about that?</line>
				<line>T-Rex: Upon inspection: basically? The birds DID want to eat people in his movie. But that&apos;s a scary concept, right? Birds hungering for flesh is bad news for everyone!</line>
				<line>T-Rex: It&apos;s, uh, it&apos;s especially bad for fleshy dudes.</line>
				<line>Utahraptor: You&apos;re dancing around the REAL threat here, T-Rex: ZOMBIE MOSQUITOES.</line>
				<line>T-Rex: OH</line>
				<line>T-Rex: MY</line>
				<line>T-Rex: GOD</line>
				<line>T-Rex: You&apos;re right! The infection would spread quickly and nearly invisibly! And mosquitoes already want blood, so it&apos;s not like they need THAT much encouragement to become zombies. Man!</line>
				<line>Utahraptor: I guess we can only hope that the insect kingdom never becomes zombified?</line>
				<line>T-Rex: I guess so!!</line>
				<line>Narrator: 28 DAYS LATER:</line>
				<line>Off-panel: Save us! Save us from the zombie butterflies!</line>
				<line>T-Rex: WEAAAAAAAK</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1012</url>
		<title>finally this spot was meant as an archive title but i mostly use it to talk about how many showers i&apos;ve had today (wednesday, so far: one and one half)</title>
		<body>
			<panel>
				<line>T-Rex: Hello Morris! How are you today?</line>
				<line>Morris: oh hello there t-rex! it&apos;s super nice to see a friendly face today</line>
				<line>T-Rex: It&apos;s nice to see you too, Morris!</line>
				<line>Morris: aw shucks t-rex, you&apos;re a real good friend, you know that? a real good friend. anyway, you should be extra careful not to eat me today or anything because i guess i got turned into a zombie last night! today has definitely had its share of challenges for me, huh</line>
				<line>T-Rex: What?! Seriously?</line>
				<line>Morris: yeah! and i dunno what i did wrong because i went to bed like normal last night but when i woke up in the morning i had zombie disease! so it was real embarrassing</line>
				<line>Morris:but don&apos;t worry, i&apos;m not going to turn you guys into zombies too! i wouldn&apos;t be a very good friend if i did that, and the book i got at the centre says that being a good friend is awful important!</line>
				<line>Morris:i always try to be a good friend, even though things pretty often don&apos;t work out very well for me in the end</line>
				<line>Utahraptor: Aw, Morris! You don&apos;t look very undead to me!</line>
				<line>Morris: aw, that probably just means i&apos;ve messed up somewhere again. the problem is that i&apos;m not real good at biting people, you know? and biting people is all zombies do! i didn&apos;t know, but being a zombie is an awful hassle</line>
				<line>Utahraptor: I&apos;m pretty sure you&apos;re not actually undead, Morris! Normally zombies can&apos;t talk. </line>
				<line>T-Rex: Yeah, or work on their Life Challenges! I think you&apos;re FINE.</line>
				<line>Morris: you mean i&apos;m doing that wrong too? oh goodness, i must be the worst zombie going. plus that book i got from the centre is way overdue! </line>
				<line>T-Rex: It&apos;s not too late to return it, Morris! </line>
				<line>Morris: but i promised the staff there that i&apos;d be extra certain to return it on time! </line>
				<line>Morris: i guess i&apos;m probably off your christmas card list this year, huh t-rex</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1013</url>
		<title>since pi is universal, any sufficiently-advance alien culture probably has a similar joke to feynman&apos;s about pi.  it is a Universal Joke.  that&apos;s nuts!</title>
		<body>
			<panel>
				<line>T-Rex: I am jealous of physicist RICHARD FEYNMAN.</line>
				<line>T-Rex: Aaaand here&apos;s why!</line>
				<line>T-Rex: Dude made a joke about the 762nd decimal place of pi! At that point, there&apos;s a sequence of six nines in a row, and his joke was that he&apos;d like to memorize pi up to that point, so that when reciting he could end with &quot;9, 9, 9, 9, 9, 9... and so on.&quot; Others had noticed it before FEYNMAN was the first to make a joke about it, and now his joke is encoded into the very fabric of the universe!</line>
				<line>Utahraptor: And that makes you irrationally jealous?</line>
				<line>T-Rex:  Hells yes!</line>
				<line>T-Rex: Feynman has a JOKE encoded into pi - transcendental immortality in the circumference of a circle! That&apos;s something for the ol&apos; resume, eh?</line>
				<line>Utahraptor: I guess!</line>
				<line>T-Rex: I&apos;m gonna make my own universal constant joke now, and I&apos;m gonna need you to tell people about it.</line>
				<line>T-Rex: So! Why do people start getting afraid at the 2501st digit of e? Because 7 8 9! There&apos;s a sequence of &quot;789&quot; that starts there, and it sounds like &quot;seven ate nine&quot;! This is definitely called &quot;T-Rex&apos;s Hilarious e joke&quot;, okay?</line>
			</panel>
		</body>
	</transcription>
	<transcription>
		<url>qwantz.com/index.php?comic=1015</url>
		<title>saying that is like unwrapping the paper on the present that is old age</title>
		<body>
			<panel>
				<line>Narrator : T-REX AS AN OLD MAN COMICS</line>
				<line>T-Rex: Guys, I&apos;m still the same T-Rex I always was!</line>
				<line>T-Rex: I&apos;m even pretty well preserved: check it out, Dromiceiomimus! Barely any wrinkles!</line>
				<line>Domiceiomimus: That&apos;s nice, T-Rex.</line>
				<line>T-Rex: Also I&apos;ve got my trademark &quot;nice calves&quot; and &quot;young smile&quot;. I&apos;m so old! AND YET, I&apos;m so sexy!</line>
				<line>Utharaptor: Hey, you know what&apos;s rad? Old dudes not talking about how sexy they are.</line>
				<line>T-Rex: I&apos;m young at heart!</line>